//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TODTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class OMNITURE_DATA
    {
        public int SEQUENCE_ID { get; set; }
        public string FW_ID { get; set; }
        public System.DateTime REP_GEN_DATE { get; set; }
        public System.DateTime FW_START_DATE { get; set; }
        public System.DateTime FW_END_DATE { get; set; }
        public byte[] LANGUAGE_REPORT { get; set; }
        public byte[] MANUAL_TITLE { get; set; }
        public byte[] PRODUCT_NAME { get; set; }
        public byte[] PRODUCT_CODE { get; set; }
        public byte[] PUBLICATION_ID { get; set; }
        public byte[] TOD_REPORT { get; set; }
        public byte[] TOPIC_GUID { get; set; }
        public byte[] TOPIC_TITLE { get; set; }
        public string OMNITURE_STATUS { get; set; }
    
        public virtual FW_CALENDAR FW_CALENDAR { get; set; }
    }
}
