//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TODTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Status { get; set; }
        public string Brand { get; set; }
        public string Category { get; set; }
        public string Product_Class { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Last_Updated { get; set; }
        public string Last_Updated_By { get; set; }
        public string Created { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Effective_From { get; set; }
        public Nullable<System.DateTime> Expiring_On { get; set; }
    }
}
