//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TODTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOD_DATA
    {
        public int SEQUENCE_ID { get; set; }
        public int CE_SEQUENCE_ID { get; set; }
        public string FW_ID { get; set; }
        public System.DateTime REP_GEN_DATE { get; set; }
        public System.DateTime FW_START_DATE { get; set; }
        public System.DateTime FW_END_DATE { get; set; }
        public string REPORTER { get; set; }
        public string ISSUE_TYPE { get; set; }
        public string SUMMARY { get; set; }
        public string LANGUAGE { get; set; }
        public string DEFECT_SOURCE { get; set; }
        public string DEFECT_TYPE { get; set; }
        public string PRODUCT_CATEGORY { get; set; }
        public string COMPONENT_S { get; set; }
        public string PRIORITY_LEVEL { get; set; }
        public string ASSIGNEE { get; set; }
        public string DESCRIPTION { get; set; }
        public string TOD_STATUS { get; set; }
    
        public virtual FW_CALENDAR FW_CALENDAR { get; set; }
    }
}
