//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TODTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOD_TransactionLog
    {
        public int logId { get; set; }
        public string logtype { get; set; }
        public string logdate { get; set; }
        public string logMessage { get; set; }
        public string logStatus { get; set; }
    }
}
